theme="dark_plus"
[editor]
bufferline="always"		

[keys.normal]
"(" = "goto_prev_paragraph"
")" = "goto_next_paragraph"
"Y" = ["extend_line","yank"]
"0" = "goto_line_start"
"V" = ["goto_line_start","select_mode"]
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-k" = "jump_view_up"
"C-j" = "jump_view_down"

[keys.select]
"(" = "goto_prev_paragraph"
")" = "goto_next_paragraph"
"Y" = ["extend_line","yank"]
"0" = "goto_line_start"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
