# ~/.config/helix/languages.toml
[language-server.gpt]
command = "helix-gpt"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]


[[language]]
name = "python"
language-servers = [ "pyright", "ruff","gpt" ]
auto-format = true


